import { RealEstateCatalogItem } from '../types/financial';

export const INITIAL_REAL_ESTATE_CATALOG: RealEstateCatalogItem[] = [
  {
    id: 're-cat-1',
    name: 'Apex Residential Apartments',
    propertyType: 'MULTIFAMILY',
    address: '482 Metro Parkway, Sector 4',
    unitsOrSqft: '48 Residential Units',
    purchasePrice: 4200000,
    grossRent: 410000,
    vacancyRate: 0.05,
    propertyTax: 52000,
    insurance: 18000,
    maintenance: 36000,
    managementFeePct: 0.05,
    utilities: 22000,
    capexReserve: 15000,
    ltvRatio: 0.70,
    interestRate: 0.055,
    interestType: 'FIXED',
    projectedAppreciationRate: 0.042,
    capRate: 0.058,
    description: 'A 48-unit Class-B apartment complex with steady occupancy, updated amenities, and strong value-add potential through unit renovations.',
    highlights: [
      '95% Average Historical Occupancy',
      'Value-add rent upside of $150/unit post-renovation',
      'Submarket job growth averaging 3.8% annually'
    ]
  },
  {
    id: 're-cat-2',
    name: 'Silicon Plaza Tech Office Tower',
    propertyType: 'OFFICE',
    address: '100 Innovation Way, Financial District',
    unitsOrSqft: '85,000 Sq. Ft. Class-A Office',
    purchasePrice: 12500000,
    grossRent: 1350000,
    vacancyRate: 0.08,
    propertyTax: 165000,
    insurance: 48000,
    maintenance: 95000,
    managementFeePct: 0.04,
    utilities: 82000,
    capexReserve: 45000,
    ltvRatio: 0.65,
    interestRate: 0.0625,
    interestType: 'FLOATING',
    projectedAppreciationRate: 0.035,
    capRate: 0.061,
    description: 'High-tech office building featuring long-term credit-tenant leases with annual 3% escalation clauses.',
    highlights: [
      'Credit tenants with 7.2-year WALT (Weighted Average Lease Term)',
      'LEED Gold Certified energy infrastructure',
      'Underground parking deck generating $85k/yr ancillary income'
    ]
  },
  {
    id: 're-cat-3',
    name: 'Crossroads Industrial Logistics Hub',
    propertyType: 'INDUSTRIAL',
    address: '88 Logistics Boulevard, Airport Corridor',
    unitsOrSqft: '140,000 Sq. Ft. Warehouse',
    purchasePrice: 8800000,
    grossRent: 820000,
    vacancyRate: 0.03,
    propertyTax: 98000,
    insurance: 32000,
    maintenance: 42000,
    managementFeePct: 0.03,
    utilities: 28000,
    capexReserve: 25000,
    ltvRatio: 0.68,
    interestRate: 0.0525,
    interestType: 'FIXED',
    projectedAppreciationRate: 0.050,
    capRate: 0.065,
    description: 'Prime distribution logistics warehouse with 32ft clear ceiling heights and 24 loading docks next to major interstate highway.',
    highlights: [
      'Triple-Net (NNN) lease structure minimizing owner expenses',
      'E-commerce demand driving 5.0% projected annual appreciation',
      'Low structural maintenance requirement'
    ]
  },
  {
    id: 're-cat-4',
    name: 'Grand Avenue Promenade Retail Center',
    propertyType: 'RETAIL',
    address: '1200 Grand Avenue, Downtown Core',
    unitsOrSqft: '28,000 Sq. Ft. Strip Retail',
    purchasePrice: 3600000,
    grossRent: 380000,
    vacancyRate: 0.06,
    propertyTax: 48000,
    insurance: 16000,
    maintenance: 26000,
    managementFeePct: 0.05,
    utilities: 18000,
    capexReserve: 12000,
    ltvRatio: 0.65,
    interestRate: 0.0575,
    interestType: 'FIXED',
    projectedAppreciationRate: 0.038,
    capRate: 0.067,
    description: 'High-foot-traffic retail promenade anchored by a national grocery chain, specialty coffee shop, and boutique fitness studio.',
    highlights: [
      'Anchored by 15-year master lease grocery tenant',
      'Signalized corner intersection with 42,000 vehicles/day',
      'Pass-through CAM cost reimbursements'
    ]
  },
  {
    id: 're-cat-5',
    name: 'Metropolitan Mixed-Use Innovation Center',
    propertyType: 'MIXED_USE',
    address: '500 Central Avenue, Urban District',
    unitsOrSqft: '60 Units + 15,000 Sq. Ft. Retail',
    purchasePrice: 15000000,
    grossRent: 1620000,
    vacancyRate: 0.05,
    propertyTax: 195000,
    insurance: 58000,
    maintenance: 110000,
    managementFeePct: 0.045,
    utilities: 92000,
    capexReserve: 55000,
    ltvRatio: 0.70,
    interestRate: 0.060,
    interestType: 'FLOATING',
    projectedAppreciationRate: 0.048,
    capRate: 0.069,
    description: 'Flagship mixed-use urban development combining luxury residential micro-suites above ground-floor artisanal dining and coworking.',
    highlights: [
      'Diversified revenue streams (Residential + Commercial + Parking)',
      'Submarket transit-oriented zone with high rental growth',
      'Smart building tech lowers utility overhead by 18%'
    ]
  },
  {
    id: 're-cat-6',
    name: 'Oakwood Single-Family Rental Cluster',
    propertyType: 'RESIDENTIAL',
    address: 'Oakwood Estates, Suburban Submarket',
    unitsOrSqft: '12 Single-Family Homes',
    purchasePrice: 2950000,
    grossRent: 285000,
    vacancyRate: 0.04,
    propertyTax: 38000,
    insurance: 14000,
    maintenance: 24000,
    managementFeePct: 0.07,
    utilities: 8000,
    capexReserve: 12000,
    ltvRatio: 0.75,
    interestRate: 0.055,
    interestType: 'FIXED',
    projectedAppreciationRate: 0.045,
    capRate: 0.057,
    description: 'A portfolio of 12 newly constructed 4-bedroom single-family homes in top-rated school districts with long-term family tenants.',
    highlights: [
      '100% single-family detached homes with fenced yards',
      'High retention rates & low turnover expense',
      'Individual utility sub-metering'
    ]
  },
  {
    id: 're-cat-7',
    name: 'Valley Medical Outpatient Pavilion',
    propertyType: 'MEDICAL',
    address: '320 Health Sciences Way, Medical District',
    unitsOrSqft: '35,000 Sq. Ft. Medical Facility',
    purchasePrice: 6400000,
    grossRent: 620000,
    vacancyRate: 0.02,
    propertyTax: 72000,
    insurance: 24000,
    maintenance: 38000,
    managementFeePct: 0.035,
    utilities: 32000,
    capexReserve: 20000,
    ltvRatio: 0.65,
    interestRate: 0.0535,
    interestType: 'FIXED',
    projectedAppreciationRate: 0.040,
    capRate: 0.065,
    description: 'Specialized healthcare outpatient building featuring surgery suites, imaging labs, and regional health network lease guaranties.',
    highlights: [
      '98% historical occupancy rate with 10-year average leases',
      'High tenant capital investment in specialized fit-outs',
      'Resilient healthcare sector demand profile'
    ]
  },
  {
    id: 're-cat-8',
    name: 'Beacon Bay Boutique Waterfront Lodge',
    propertyType: 'HOTEL',
    address: '1 Ocean Drive, Coastal Resort Zone',
    unitsOrSqft: '36 Luxury Guest Suites',
    purchasePrice: 5100000,
    grossRent: 740000,
    vacancyRate: 0.18, // Seasonal vacancy
    propertyTax: 62000,
    insurance: 28000,
    maintenance: 55000,
    managementFeePct: 0.08,
    utilities: 48000,
    capexReserve: 30000,
    ltvRatio: 0.60,
    interestRate: 0.065,
    interestType: 'FLOATING',
    projectedAppreciationRate: 0.038,
    capRate: 0.071,
    description: 'High-yield hospitality asset benefiting from luxury eco-tourism demand, private beach access, and wedding event bookings.',
    highlights: [
      'Average Daily Rate (ADR) of $340/night with premium seasonal spikes',
      'High Cap Rate (7.1%) yielding strong cash returns',
      'On-site restaurant & bar contributing $180k ancillary margin'
    ]
  }
];
